kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-volume
  namespace: cicd
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
